In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [29]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [28]:
for i in df['Category']:
    if i=='spam':
        print(1)
    else:
        print(0)
   
       

0
0
1
0
0
1
0
0
1
1
0
1
1
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
1
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
1
1
0
1
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
1
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
1
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
1
0
1
0
1
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
0


In [39]:
def spam_filters(x):
        if x=="spam":
            return 1
        return 0

In [40]:
df['spam']=df['Category'].apply(spam_filters)

In [ ]:
#yada boylede yapılabilirdi
# df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [41]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [42]:
df['Category'].value_counts() # imbalanced data set

ham     4825
spam     747
Name: Category, dtype: int64

In [43]:
X_train,X_test,y_train,y_test=train_test_split(df['Message'],df['spam'],test_size=0.2)

In [44]:
X_train.shape

(4457,)

In [45]:
X_test.shape

(1115,)

In [46]:
y_train.shape

(4457,)

In [47]:
y_test.shape

(1115,)

In [48]:
X_train[0:4]

2348                       But i dint slept in afternoon.
1174                            Ü dun need to pick ur gf?
3228         Wife.how she knew the time of murder exactly
3191    Hi neva worry bout da truth coz the truth will...
Name: Message, dtype: object

In [49]:
type(X_train.values)

numpy.ndarray

# Create bag of words representation using CountVectorizer

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

In [51]:
v=CountVectorizer()

In [52]:
X_train_cv=v.fit_transform(X_train)
X_train_cv

<4457x7758 sparse matrix of type '<class 'numpy.int64'>'
	with 59150 stored elements in Compressed Sparse Row format>

In [54]:
X_train_cv.shape

(4457, 7758)

In [55]:
x_train_array=X_train_cv.toarray()

In [56]:
x_train_array.shape

(4457, 7758)

In [68]:
v.get_feature_names_out()[1574]

'but'

In [67]:
v.vocabulary_

{'but': 1574,
 'dint': 2339,
 'slept': 6245,
 'in': 3671,
 'afternoon': 858,
 'dun': 2502,
 'need': 4767,
 'to': 6947,
 'pick': 5242,
 'ur': 7213,
 'gf': 3147,
 'wife': 7524,
 'how': 3552,
 'she': 6091,
 'knew': 3989,
 'the': 6826,
 'time': 6916,
 'of': 4936,
 'murder': 4685,
 'exactly': 2702,
 'hi': 3455,
 'neva': 4793,
 'worry': 7615,
 'bout': 1449,
 'da': 2141,
 'truth': 7072,
 'coz': 2047,
 'will': 7533,
 'lead': 4084,
 'me': 4436,
 'heart': 3410,
 'it': 3790,
 'least': 4091,
 'unique': 7176,
 'person': 5204,
 'like': 4143,
 'deserve': 2269,
 'sleep': 6238,
 'tight': 6908,
 'or': 5019,
 'morning': 4620,
 'your': 7728,
 'free': 2997,
 'ringtone': 5811,
 'is': 3778,
 'waiting': 7370,
 'be': 1272,
 'collected': 1894,
 'simply': 6193,
 'text': 6797,
 'password': 5145,
 'mix': 4556,
 '85069': 678,
 'verify': 7283,
 'get': 3137,
 'usher': 7237,
 'and': 966,
 'britney': 1512,
 'fml': 2925,
 'po': 5307,
 'box': 1453,
 '5249': 553,
 'mk17': 4559,
 '92h': 724,
 '450ppw': 500,
 '16': 316,
 'o

In [69]:
x_train_array[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [75]:
np.where(x_train_array[0]!=0)

(array([ 858, 1574, 2339, 3671, 6245], dtype=int64),)

In [91]:
x_train_array[0][1574]

1

In [98]:
X_train[0:][1174]

'Ü dun need to pick ur gf?'

# Train the naive bayes model

In [99]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB

In [100]:
model = MultinomialNB()

In [101]:
model.fit(X_train_cv,y_train)

MultinomialNB()

In [102]:
x_test_cv=v.transform(X_test)

In [103]:
from sklearn.metrics import classification_report

In [104]:
y_pred=model.predict(x_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       955
           1       0.97      0.87      0.91       160

    accuracy                           0.98      1115
   macro avg       0.97      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [105]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

# Train the model using sklearn pipeline and reduce number of lines of code

In [106]:
from sklearn.pipeline import Pipeline

In [107]:
clf=Pipeline([('vectorizer',CountVectorizer()),
             ('model',MultinomialNB())])

In [108]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('model', MultinomialNB())])

In [109]:
y_pred_clf=clf.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       955
           1       0.97      0.87      0.91       160

    accuracy                           0.98      1115
   macro avg       0.97      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115

